[versions]
agp = "8.12.3"
appcompat = "1.7.1"
converterGson = "2.11.0"
fragmentKtx = "1.6.2"
gradle = "8.5.2"
gson = "2.10.1"
kotlin = "2.0.0"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.9.1"
activityCompose = "1.10.1"
composeBom = "2025.06.01"
lifecycleViewmodelCompose = "2.9.1"
material = "1.11.0"
navigationCompose = "2.9.1"
preference = "1.2.1"
preferenceKtx = "1.2.1"
recyclerview = "1.4.0"
retrofit = "2.11.0"
securityCrypto = "1.1.0"
strongswanAndroidSdk = "5.9.5"
viewpager2 = "1.0.0"
workRuntimeKtx = "2.10.2"
loggingInterceptor = "4.12.0"
tvMaterial = "1.0.1"
foundation = "1.9.0"
playServicesAuth = "21.2.0"
mockwebserver = "4.12.0"

# OpenVPN Libraries Catalog Definitions
android-gradle-plugin = "8.9.3"
androidx-activity = "1.10.1"
androidx-annotation = "1.9.1"
androidx-appcompat = "1.7.1"
android-view-material = "1.12.0"
androidx-core-ktx = "1.16.0"
androidx-fragment-ktx = "1.8.8"
androidx-preference-ktx = "1.2.1"
androidx-webkit = "1.14.0"
androidx-lifecycle-viewmodel-ktx = "2.9.2"
androidx-lifecycle-runtime-ktx = "2.9.2"
androidx-security-crypto = "1.1.0-beta01"
androidx-constraintlayout = "2.2.1"
androidx-cardview = "1.0.0"
androidx-recyclerview = "1.4.0"
androidx-viewpager2 = "1.1.0"
bouncycastle = "1.69"
mpandroidchart = "v3.1.0"
square-okhttp = "4.10.0"

# Test
androidx-test-core = "1.6.1"
mockito-core = "4.8.1"
robolectric = "4.10.2"
# End OpenVPN Libraries Catalog Definitions

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-preference = { module = "androidx.preference:preference", version.ref = "preference" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-security-crypto = { module = "androidx.security:security-crypto", version.ref = "securityCrypto" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
material = { module = "com.google.android.material:material", version.ref = "material" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
strongswan-android-sdk = { module = "org.strongswan.android:strongswan-android-sdk", version.ref = "strongswanAndroidSdk" }
androidx-tv-material = { group = "androidx.tv", name = "tv-material", version.ref = "tvMaterial" }
androidx-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation" }
play-services-auth = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "playServicesAuth" }
mockwebserver = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "mockwebserver" }

# OpenVPN Libraries Catalog Definitions
android-view-material = { group = "com.google.android.material", name = "material", version.ref = "android-view-material" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "androidx-annotation" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "androidx-activity"}
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidx-activity"}
androidx-cardview = { group = "androidx.cardview", name = "cardview", version.ref = "androidx-cardview" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-webkit = { group = "androidx.webkit", name = "webkit", version.ref = "androidx-webkit" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle-viewmodel-ktx" }
mpandroidchart = { group = "com.github.PhilJay", name = "MPAndroidChart", version.ref = "mpandroidchart" }
org-bouncycastle-bcprov-jdk15on = { group = "org.bouncycastle", name = "bcprov-jdk15on", version.ref = "bouncycastle" }
org-bouncycastle-bcprov-ext-jdk15on = { group = "org.bouncycastle", name = "bcprov-ext-jdk15on", version.ref = "bouncycastle" }
org-bouncycastle-bcpkix-jdk15on = { group = "org.bouncycastle", name = "bcpkix-jdk15on", version.ref = "bouncycastle" }
org-bouncycastle-bcmail-jdk15on = { group = "org.bouncycastle", name = "bcmail-jdk15on", version.ref = "bouncycastle" }
org-bouncycastle-bcpg-jdk15on = { group = "org.bouncycastle", name = "bcpg-jdk15on", version.ref = "bouncycastle" }
kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
square-okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "square-okhttp" }

# Test
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidx-test-core" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito-core" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }


# End openVPN Libraries Catalog Definitions

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
